import type { Fighter } from './types'
import { fighterAvatar } from './avatar'
import { fighterHeightCm } from './fighter-heights'

/**
 * Curated fighter profiles for recent champions.
 * Records & timelines approximate public UFC history as of Oct 2026 research
 * (UFC.com athletes/weight-class pages + Wikipedia title lineages).
 */
const FIGHTERS_RAW = [
  {
    id: 'ciryl-gane',
    name: 'Ciryl Gane',
    nickname: 'Bon Gamin',
    imageUrl: fighterAvatar('Ciryl Gane'),
    country: 'France',
    record: { wins: 14, losses: 2, draws: 0, noContests: 1 },
    weightClassIds: ['mens-heavyweight'],
    rankingTimeline: [
      { date: '2020-09', rank: 5, weightClassId: 'mens-heavyweight' },
      { date: '2021-08', rank: 'C', weightClassId: 'mens-heavyweight', note: 'Interim champion' },
      { date: '2022-01', rank: 1, weightClassId: 'mens-heavyweight' },
      { date: '2026-06', rank: 'C', weightClassId: 'mens-heavyweight', note: 'Listed UFC titleholder' },
    ],
    weightClassChanges: [
      {
        date: '2019-08',
        fromWeightClassId: null,
        toWeightClassId: 'mens-heavyweight',
        reason: 'UFC debut at heavyweight',
      },
    ],
  },
  {
    id: 'tom-aspinall',
    name: 'Tom Aspinall',
    imageUrl: fighterAvatar('Tom Aspinall'),
    country: 'United Kingdom',
    record: { wins: 15, losses: 3, draws: 0 },
    weightClassIds: ['mens-heavyweight'],
    rankingTimeline: [
      { date: '2022-07', rank: 8, weightClassId: 'mens-heavyweight' },
      { date: '2023-11', rank: 'C', weightClassId: 'mens-heavyweight', note: 'Interim champion' },
      { date: '2025-06', rank: 'C', weightClassId: 'mens-heavyweight', note: 'Promoted undisputed' },
    ],
    weightClassChanges: [
      {
        date: '2020-07',
        fromWeightClassId: null,
        toWeightClassId: 'mens-heavyweight',
        reason: 'UFC debut at heavyweight',
      },
    ],
  },
  {
    id: 'jon-jones',
    name: 'Jon Jones',
    nickname: 'Bones',
    imageUrl: fighterAvatar('Jon Jones'),
    country: 'United States',
    record: { wins: 28, losses: 1, draws: 0, noContests: 1 },
    weightClassIds: ['mens-heavyweight', 'mens-light-heavyweight'],
    rankingTimeline: [
      { date: '2011-03', rank: 'C', weightClassId: 'mens-light-heavyweight' },
      { date: '2020-08', rank: 'NR', weightClassId: 'mens-light-heavyweight', note: 'Vacated LHW' },
      { date: '2023-03', rank: 'C', weightClassId: 'mens-heavyweight' },
      { date: '2025-06', rank: 'NR', weightClassId: 'mens-heavyweight', note: 'Retired / vacated' },
    ],
    weightClassChanges: [
      {
        date: '2008-08',
        fromWeightClassId: null,
        toWeightClassId: 'mens-light-heavyweight',
        reason: 'UFC debut at light heavyweight',
      },
      {
        date: '2023-03',
        fromWeightClassId: 'mens-light-heavyweight',
        toWeightClassId: 'mens-heavyweight',
        reason: 'Moved up for heavyweight title vs Ciryl Gane',
      },
    ],
  },
  {
    id: 'francis-ngannou',
    name: 'Francis Ngannou',
    nickname: 'The Predator',
    imageUrl: fighterAvatar('Francis Ngannou'),
    country: 'Cameroon',
    record: { wins: 17, losses: 3, draws: 0 },
    weightClassIds: ['mens-heavyweight'],
    rankingTimeline: [
      { date: '2018-01', rank: 3, weightClassId: 'mens-heavyweight' },
      { date: '2021-03', rank: 'C', weightClassId: 'mens-heavyweight' },
      { date: '2023-01', rank: 'NR', weightClassId: 'mens-heavyweight', note: 'Left UFC' },
    ],
    weightClassChanges: [
      {
        date: '2015-12',
        fromWeightClassId: null,
        toWeightClassId: 'mens-heavyweight',
        reason: 'UFC debut at heavyweight',
      },
    ],
  },
  {
    id: 'stipe-miocic',
    name: 'Stipe Miocic',
    imageUrl: fighterAvatar('Stipe Miocic'),
    country: 'United States',
    record: { wins: 20, losses: 5, draws: 0 },
    weightClassIds: ['mens-heavyweight'],
    rankingTimeline: [
      { date: '2016-05', rank: 'C', weightClassId: 'mens-heavyweight' },
      { date: '2018-07', rank: 1, weightClassId: 'mens-heavyweight' },
      { date: '2019-08', rank: 'C', weightClassId: 'mens-heavyweight' },
      { date: '2021-03', rank: 2, weightClassId: 'mens-heavyweight' },
    ],
    weightClassChanges: [
      {
        date: '2010-10',
        fromWeightClassId: null,
        toWeightClassId: 'mens-heavyweight',
        reason: 'UFC debut at heavyweight',
      },
    ],
  },
  {
    id: 'carlos-ulberg',
    name: 'Carlos Ulberg',
    nickname: 'Black Jag',
    imageUrl: fighterAvatar('Carlos Ulberg'),
    country: 'New Zealand',
    record: { wins: 15, losses: 1, draws: 0 },
    weightClassIds: ['mens-light-heavyweight'],
    rankingTimeline: [
      { date: '2024-06', rank: 8, weightClassId: 'mens-light-heavyweight' },
      { date: '2026-04', rank: 'C', weightClassId: 'mens-light-heavyweight' },
    ],
    weightClassChanges: [
      {
        date: '2021-03',
        fromWeightClassId: null,
        toWeightClassId: 'mens-light-heavyweight',
        reason: 'UFC debut at light heavyweight',
      },
    ],
  },
  {
    id: 'alex-pereira',
    name: 'Alex Pereira',
    nickname: 'Poatan',
    imageUrl: fighterAvatar('Alex Pereira'),
    country: 'Brazil',
    record: { wins: 12, losses: 3, draws: 0 },
    weightClassIds: [
      'mens-heavyweight',
      'mens-light-heavyweight',
      'mens-middleweight',
    ],
    rankingTimeline: [
      { date: '2022-11', rank: 'C', weightClassId: 'mens-middleweight' },
      { date: '2023-04', rank: 1, weightClassId: 'mens-middleweight' },
      { date: '2023-11', rank: 'C', weightClassId: 'mens-light-heavyweight' },
      { date: '2025-03', rank: 1, weightClassId: 'mens-light-heavyweight' },
      { date: '2025-10', rank: 'C', weightClassId: 'mens-light-heavyweight' },
      { date: '2026-04', rank: 'NR', weightClassId: 'mens-light-heavyweight', note: 'Vacated for HW' },
    ],
    weightClassChanges: [
      {
        date: '2021-11',
        fromWeightClassId: null,
        toWeightClassId: 'mens-middleweight',
        reason: 'UFC debut at middleweight',
      },
      {
        date: '2023-11',
        fromWeightClassId: 'mens-middleweight',
        toWeightClassId: 'mens-light-heavyweight',
        reason: 'Moved up after middleweight title run',
      },
      {
        date: '2026-04',
        fromWeightClassId: 'mens-light-heavyweight',
        toWeightClassId: 'mens-heavyweight',
        reason: 'Vacated LHW to challenge at heavyweight',
      },
    ],
  },
  {
    id: 'magomed-ankalaev',
    name: 'Magomed Ankalaev',
    imageUrl: fighterAvatar('Magomed Ankalaev'),
    country: 'Russia',
    record: { wins: 20, losses: 1, draws: 1 },
    weightClassIds: ['mens-light-heavyweight'],
    rankingTimeline: [
      { date: '2022-12', rank: 2, weightClassId: 'mens-light-heavyweight' },
      { date: '2025-03', rank: 'C', weightClassId: 'mens-light-heavyweight' },
      { date: '2025-10', rank: 1, weightClassId: 'mens-light-heavyweight' },
    ],
    weightClassChanges: [
      {
        date: '2018-10',
        fromWeightClassId: null,
        toWeightClassId: 'mens-light-heavyweight',
        reason: 'UFC debut at light heavyweight',
      },
    ],
  },
  {
    id: 'jamahal-hill',
    name: 'Jamahal Hill',
    nickname: 'Sweet Dreams',
    imageUrl: fighterAvatar('Jamahal Hill'),
    country: 'United States',
    record: { wins: 12, losses: 2, draws: 0, noContests: 1 },
    weightClassIds: ['mens-light-heavyweight'],
    rankingTimeline: [
      { date: '2023-01', rank: 'C', weightClassId: 'mens-light-heavyweight' },
      { date: '2023-07', rank: 'NR', weightClassId: 'mens-light-heavyweight', note: 'Vacated injured' },
    ],
    weightClassChanges: [
      {
        date: '2020-01',
        fromWeightClassId: null,
        toWeightClassId: 'mens-light-heavyweight',
        reason: 'UFC debut at light heavyweight',
      },
    ],
  },
  {
    id: 'jiri-prochazka',
    name: 'Jiří Procházka',
    nickname: 'BJP',
    imageUrl: fighterAvatar('Jiri Prochazka'),
    country: 'Czechia',
    record: { wins: 31, losses: 5, draws: 1 },
    weightClassIds: ['mens-light-heavyweight'],
    rankingTimeline: [
      { date: '2022-06', rank: 'C', weightClassId: 'mens-light-heavyweight' },
      { date: '2022-11', rank: 'NR', weightClassId: 'mens-light-heavyweight', note: 'Vacated injured' },
      { date: '2024-06', rank: 2, weightClassId: 'mens-light-heavyweight' },
    ],
    weightClassChanges: [
      {
        date: '2021-07',
        fromWeightClassId: null,
        toWeightClassId: 'mens-light-heavyweight',
        reason: 'UFC debut at light heavyweight',
      },
    ],
  },
  {
    id: 'sean-strickland',
    name: 'Sean Strickland',
    nickname: 'Tarzan',
    imageUrl: fighterAvatar('Sean Strickland'),
    country: 'United States',
    record: { wins: 29, losses: 7, draws: 0 },
    weightClassIds: ['mens-middleweight', 'mens-welterweight'],
    rankingTimeline: [
      { date: '2023-09', rank: 'C', weightClassId: 'mens-middleweight' },
      { date: '2024-01', rank: 1, weightClassId: 'mens-middleweight' },
      { date: '2026-05', rank: 'C', weightClassId: 'mens-middleweight' },
    ],
    weightClassChanges: [
      {
        date: '2014-03',
        fromWeightClassId: null,
        toWeightClassId: 'mens-welterweight',
        reason: 'UFC debut at welterweight',
      },
      {
        date: '2017-01',
        fromWeightClassId: 'mens-welterweight',
        toWeightClassId: 'mens-middleweight',
        reason: 'Permanent move up to middleweight',
      },
    ],
  },
  {
    id: 'khamzat-chimaev',
    name: 'Khamzat Chimaev',
    nickname: 'Borz',
    imageUrl: fighterAvatar('Khamzat Chimaev'),
    country: 'Sweden / Chechnya',
    record: { wins: 15, losses: 0, draws: 0 },
    weightClassIds: ['mens-middleweight', 'mens-welterweight'],
    rankingTimeline: [
      { date: '2021-09', rank: 5, weightClassId: 'mens-welterweight' },
      { date: '2023-01', rank: 3, weightClassId: 'mens-middleweight' },
      { date: '2025-08', rank: 'C', weightClassId: 'mens-middleweight' },
      { date: '2026-05', rank: 1, weightClassId: 'mens-middleweight' },
    ],
    weightClassChanges: [
      {
        date: '2020-07',
        fromWeightClassId: null,
        toWeightClassId: 'mens-welterweight',
        reason: 'UFC debut at welterweight',
      },
      {
        date: '2022-09',
        fromWeightClassId: 'mens-welterweight',
        toWeightClassId: 'mens-middleweight',
        reason: 'Moved up to middleweight',
      },
    ],
  },
  {
    id: 'dricus-du-plessis',
    name: 'Dricus du Plessis',
    nickname: 'Stillknocks',
    imageUrl: fighterAvatar('Dricus du Plessis'),
    country: 'South Africa',
    record: { wins: 23, losses: 3, draws: 0 },
    weightClassIds: ['mens-middleweight'],
    rankingTimeline: [
      { date: '2024-01', rank: 'C', weightClassId: 'mens-middleweight' },
      { date: '2025-08', rank: 1, weightClassId: 'mens-middleweight' },
    ],
    weightClassChanges: [
      {
        date: '2020-10',
        fromWeightClassId: null,
        toWeightClassId: 'mens-middleweight',
        reason: 'UFC debut at middleweight',
      },
    ],
  },
  {
    id: 'israel-adesanya',
    name: 'Israel Adesanya',
    nickname: 'The Last Stylebender',
    imageUrl: fighterAvatar('Israel Adesanya'),
    country: 'Nigeria / New Zealand',
    record: { wins: 24, losses: 5, draws: 0 },
    weightClassIds: ['mens-middleweight', 'mens-light-heavyweight'],
    rankingTimeline: [
      { date: '2019-10', rank: 'C', weightClassId: 'mens-middleweight' },
      { date: '2022-11', rank: 1, weightClassId: 'mens-middleweight' },
      { date: '2023-04', rank: 'C', weightClassId: 'mens-middleweight' },
      { date: '2023-09', rank: 2, weightClassId: 'mens-middleweight' },
    ],
    weightClassChanges: [
      {
        date: '2018-02',
        fromWeightClassId: null,
        toWeightClassId: 'mens-middleweight',
        reason: 'UFC debut at middleweight',
      },
      {
        date: '2021-03',
        fromWeightClassId: 'mens-middleweight',
        toWeightClassId: 'mens-light-heavyweight',
        reason: 'Temporary LHW title shot vs Blachowicz',
      },
      {
        date: '2021-03',
        fromWeightClassId: 'mens-light-heavyweight',
        toWeightClassId: 'mens-middleweight',
        reason: 'Returned to middleweight',
      },
    ],
  },
  {
    id: 'islam-makhachev',
    name: 'Islam Makhachev',
    imageUrl: fighterAvatar('Islam Makhachev'),
    country: 'Russia',
    record: { wins: 29, losses: 1, draws: 0 },
    weightClassIds: ['mens-welterweight', 'mens-lightweight'],
    rankingTimeline: [
      { date: '2022-10', rank: 'C', weightClassId: 'mens-lightweight' },
      { date: '2025-05', rank: 'NR', weightClassId: 'mens-lightweight', note: 'Vacated for WW' },
      { date: '2025-11', rank: 'C', weightClassId: 'mens-welterweight' },
    ],
    weightClassChanges: [
      {
        date: '2015-10',
        fromWeightClassId: null,
        toWeightClassId: 'mens-lightweight',
        reason: 'UFC debut at lightweight',
      },
      {
        date: '2025-11',
        fromWeightClassId: 'mens-lightweight',
        toWeightClassId: 'mens-welterweight',
        reason: 'Moved up and won welterweight title',
      },
    ],
  },
  {
    id: 'jack-della-maddalena',
    name: 'Jack Della Maddalena',
    imageUrl: fighterAvatar('Jack Della Maddalena'),
    country: 'Australia',
    record: { wins: 18, losses: 3, draws: 0 },
    weightClassIds: ['mens-welterweight'],
    rankingTimeline: [
      { date: '2024-09', rank: 3, weightClassId: 'mens-welterweight' },
      { date: '2025-05', rank: 'C', weightClassId: 'mens-welterweight' },
      { date: '2025-11', rank: 1, weightClassId: 'mens-welterweight' },
    ],
    weightClassChanges: [
      {
        date: '2022-02',
        fromWeightClassId: null,
        toWeightClassId: 'mens-welterweight',
        reason: 'UFC debut at welterweight',
      },
    ],
  },
  {
    id: 'belal-muhammad',
    name: 'Belal Muhammad',
    nickname: 'Remember the Name',
    imageUrl: fighterAvatar('Belal Muhammad'),
    country: 'United States',
    record: { wins: 24, losses: 4, draws: 0 },
    weightClassIds: ['mens-welterweight'],
    rankingTimeline: [
      { date: '2024-07', rank: 'C', weightClassId: 'mens-welterweight' },
      { date: '2025-05', rank: 2, weightClassId: 'mens-welterweight' },
    ],
    weightClassChanges: [
      {
        date: '2016-07',
        fromWeightClassId: null,
        toWeightClassId: 'mens-welterweight',
        reason: 'UFC debut at welterweight',
      },
    ],
  },
  {
    id: 'leon-edwards',
    name: 'Leon Edwards',
    nickname: 'Rocky',
    imageUrl: fighterAvatar('Leon Edwards'),
    country: 'United Kingdom',
    record: { wins: 22, losses: 5, draws: 0 },
    weightClassIds: ['mens-welterweight'],
    rankingTimeline: [
      { date: '2022-08', rank: 'C', weightClassId: 'mens-welterweight' },
      { date: '2024-07', rank: 1, weightClassId: 'mens-welterweight' },
    ],
    weightClassChanges: [
      {
        date: '2014-11',
        fromWeightClassId: null,
        toWeightClassId: 'mens-welterweight',
        reason: 'UFC debut at welterweight',
      },
    ],
  },
  {
    id: 'kamaru-usman',
    name: 'Kamaru Usman',
    nickname: 'The Nigerian Nightmare',
    imageUrl: fighterAvatar('Kamaru Usman'),
    country: 'Nigeria / United States',
    record: { wins: 20, losses: 4, draws: 0 },
    weightClassIds: ['mens-welterweight'],
    rankingTimeline: [
      { date: '2019-03', rank: 'C', weightClassId: 'mens-welterweight' },
      { date: '2022-08', rank: 1, weightClassId: 'mens-welterweight' },
    ],
    weightClassChanges: [
      {
        date: '2015-07',
        fromWeightClassId: null,
        toWeightClassId: 'mens-welterweight',
        reason: 'UFC debut at welterweight',
      },
    ],
  },
  {
    id: 'justin-gaethje',
    name: 'Justin Gaethje',
    nickname: 'The Highlight',
    imageUrl: fighterAvatar('Justin Gaethje'),
    country: 'United States',
    record: { wins: 28, losses: 5, draws: 0 },
    weightClassIds: ['mens-lightweight'],
    rankingTimeline: [
      { date: '2020-05', rank: 'C', weightClassId: 'mens-lightweight', note: 'Interim' },
      { date: '2020-10', rank: 2, weightClassId: 'mens-lightweight' },
      { date: '2026-01', rank: 'C', weightClassId: 'mens-lightweight', note: 'Interim' },
      { date: '2026-06', rank: 'C', weightClassId: 'mens-lightweight' },
    ],
    weightClassChanges: [
      {
        date: '2017-07',
        fromWeightClassId: null,
        toWeightClassId: 'mens-lightweight',
        reason: 'UFC debut at lightweight',
      },
    ],
  },
  {
    id: 'ilia-topuria',
    name: 'Ilia Topuria',
    nickname: 'El Matador',
    imageUrl: fighterAvatar('Ilia Topuria'),
    country: 'Spain / Georgia',
    record: { wins: 17, losses: 1, draws: 0 },
    weightClassIds: ['mens-lightweight', 'mens-featherweight'],
    rankingTimeline: [
      { date: '2024-02', rank: 'C', weightClassId: 'mens-featherweight' },
      { date: '2025-02', rank: 'NR', weightClassId: 'mens-featherweight', note: 'Vacated for LW' },
      { date: '2025-06', rank: 'C', weightClassId: 'mens-lightweight' },
      { date: '2026-06', rank: 1, weightClassId: 'mens-lightweight' },
    ],
    weightClassChanges: [
      {
        date: '2020-10',
        fromWeightClassId: null,
        toWeightClassId: 'mens-featherweight',
        reason: 'UFC debut at featherweight',
      },
      {
        date: '2025-06',
        fromWeightClassId: 'mens-featherweight',
        toWeightClassId: 'mens-lightweight',
        reason: 'Vacated FW to win lightweight title',
      },
    ],
  },
  {
    id: 'charles-oliveira',
    name: 'Charles Oliveira',
    nickname: 'do Bronx',
    imageUrl: fighterAvatar('Charles Oliveira'),
    country: 'Brazil',
    record: { wins: 35, losses: 10, draws: 0, noContests: 1 },
    weightClassIds: ['mens-lightweight', 'mens-featherweight'],
    rankingTimeline: [
      { date: '2021-05', rank: 'C', weightClassId: 'mens-lightweight' },
      { date: '2022-05', rank: 'NR', weightClassId: 'mens-lightweight', note: 'Stripped (weight miss)' },
      { date: '2022-10', rank: 1, weightClassId: 'mens-lightweight' },
    ],
    weightClassChanges: [
      {
        date: '2010-08',
        fromWeightClassId: null,
        toWeightClassId: 'mens-lightweight',
        reason: 'UFC debut (later settled at lightweight)',
      },
    ],
  },
  {
    id: 'khabib-nurmagomedov',
    name: 'Khabib Nurmagomedov',
    nickname: 'The Eagle',
    imageUrl: fighterAvatar('Khabib Nurmagomedov'),
    country: 'Russia',
    record: { wins: 29, losses: 0, draws: 0 },
    weightClassIds: ['mens-lightweight'],
    rankingTimeline: [
      { date: '2018-04', rank: 'C', weightClassId: 'mens-lightweight' },
      { date: '2021-03', rank: 'NR', weightClassId: 'mens-lightweight', note: 'Retired' },
    ],
    weightClassChanges: [
      {
        date: '2012-01',
        fromWeightClassId: null,
        toWeightClassId: 'mens-lightweight',
        reason: 'UFC debut at lightweight',
      },
    ],
  },
  {
    id: 'alexander-volkanovski',
    name: 'Alexander Volkanovski',
    nickname: 'The Great',
    imageUrl: fighterAvatar('Alexander Volkanovski'),
    country: 'Australia',
    record: { wins: 28, losses: 4, draws: 0 },
    weightClassIds: ['mens-featherweight', 'mens-lightweight'],
    rankingTimeline: [
      { date: '2019-12', rank: 'C', weightClassId: 'mens-featherweight' },
      { date: '2024-02', rank: 1, weightClassId: 'mens-featherweight' },
      { date: '2025-04', rank: 'C', weightClassId: 'mens-featherweight' },
    ],
    weightClassChanges: [
      {
        date: '2016-11',
        fromWeightClassId: null,
        toWeightClassId: 'mens-featherweight',
        reason: 'UFC debut at featherweight',
      },
      {
        date: '2023-02',
        fromWeightClassId: 'mens-featherweight',
        toWeightClassId: 'mens-lightweight',
        reason: 'Temporary LW title challenges vs Makhachev',
      },
      {
        date: '2023-10',
        fromWeightClassId: 'mens-lightweight',
        toWeightClassId: 'mens-featherweight',
        reason: 'Returned to featherweight',
      },
    ],
  },
  {
    id: 'max-holloway',
    name: 'Max Holloway',
    nickname: 'Blessed',
    imageUrl: fighterAvatar('Max Holloway'),
    country: 'United States',
    record: { wins: 28, losses: 8, draws: 0 },
    weightClassIds: ['mens-featherweight', 'mens-lightweight', 'mens-bantamweight'],
    rankingTimeline: [
      { date: '2017-06', rank: 'C', weightClassId: 'mens-featherweight' },
      { date: '2019-12', rank: 1, weightClassId: 'mens-featherweight' },
    ],
    weightClassChanges: [
      {
        date: '2012-02',
        fromWeightClassId: null,
        toWeightClassId: 'mens-featherweight',
        reason: 'UFC debut at featherweight',
      },
      {
        date: '2023-04',
        fromWeightClassId: 'mens-featherweight',
        toWeightClassId: 'mens-lightweight',
        reason: 'Bouted at lightweight / BMF',
      },
    ],
  },
  {
    id: 'conor-mcgregor',
    name: 'Conor McGregor',
    nickname: 'The Notorious',
    imageUrl: fighterAvatar('Conor McGregor'),
    country: 'Ireland',
    record: { wins: 22, losses: 7, draws: 0 },
    weightClassIds: ['mens-lightweight', 'mens-featherweight', 'mens-welterweight'],
    rankingTimeline: [
      { date: '2015-12', rank: 'C', weightClassId: 'mens-featherweight' },
      { date: '2016-11', rank: 'C', weightClassId: 'mens-lightweight' },
      { date: '2018-04', rank: 'NR', weightClassId: 'mens-lightweight', note: 'Stripped inactivity' },
    ],
    weightClassChanges: [
      {
        date: '2013-04',
        fromWeightClassId: null,
        toWeightClassId: 'mens-featherweight',
        reason: 'UFC debut at featherweight',
      },
      {
        date: '2016-11',
        fromWeightClassId: 'mens-featherweight',
        toWeightClassId: 'mens-lightweight',
        reason: 'Won lightweight title; vacated FW',
      },
    ],
  },
  {
    id: 'jose-aldo',
    name: 'José Aldo',
    imageUrl: fighterAvatar('Jose Aldo'),
    country: 'Brazil',
    record: { wins: 32, losses: 10, draws: 0 },
    weightClassIds: ['mens-bantamweight', 'mens-featherweight'],
    rankingTimeline: [
      { date: '2010-11', rank: 'C', weightClassId: 'mens-featherweight' },
      { date: '2015-12', rank: 1, weightClassId: 'mens-featherweight' },
      { date: '2016-11', rank: 'C', weightClassId: 'mens-featherweight' },
    ],
    weightClassChanges: [
      {
        date: '2010-11',
        fromWeightClassId: null,
        toWeightClassId: 'mens-featherweight',
        reason: 'Promoted as inaugural UFC featherweight champion (WEC)',
      },
      {
        date: '2019-12',
        fromWeightClassId: 'mens-featherweight',
        toWeightClassId: 'mens-bantamweight',
        reason: 'Moved down to bantamweight',
      },
    ],
  },
  {
    id: 'petr-yan',
    name: 'Petr Yan',
    nickname: 'No Mercy',
    imageUrl: fighterAvatar('Petr Yan'),
    country: 'Russia',
    record: { wins: 20, losses: 5, draws: 0 },
    weightClassIds: ['mens-bantamweight'],
    rankingTimeline: [
      { date: '2020-07', rank: 'C', weightClassId: 'mens-bantamweight' },
      { date: '2021-03', rank: 1, weightClassId: 'mens-bantamweight' },
      { date: '2025-12', rank: 'C', weightClassId: 'mens-bantamweight' },
    ],
    weightClassChanges: [
      {
        date: '2018-06',
        fromWeightClassId: null,
        toWeightClassId: 'mens-bantamweight',
        reason: 'UFC debut at bantamweight',
      },
    ],
  },
  {
    id: 'merab-dvalishvili',
    name: 'Merab Dvalishvili',
    nickname: 'The Machine',
    imageUrl: fighterAvatar('Merab Dvalishvili'),
    country: 'Georgia',
    record: { wins: 19, losses: 5, draws: 0 },
    weightClassIds: ['mens-bantamweight'],
    rankingTimeline: [
      { date: '2024-09', rank: 'C', weightClassId: 'mens-bantamweight' },
      { date: '2025-12', rank: 1, weightClassId: 'mens-bantamweight' },
    ],
    weightClassChanges: [
      {
        date: '2017-12',
        fromWeightClassId: null,
        toWeightClassId: 'mens-bantamweight',
        reason: 'UFC debut at bantamweight',
      },
    ],
  },
  {
    id: 'sean-omalley',
    name: "Sean O'Malley",
    nickname: 'Suga',
    imageUrl: fighterAvatar("Sean O'Malley"),
    country: 'United States',
    record: { wins: 18, losses: 3, draws: 0, noContests: 1 },
    weightClassIds: ['mens-bantamweight'],
    rankingTimeline: [
      { date: '2023-08', rank: 'C', weightClassId: 'mens-bantamweight' },
      { date: '2024-09', rank: 1, weightClassId: 'mens-bantamweight' },
    ],
    weightClassChanges: [
      {
        date: '2017-12',
        fromWeightClassId: null,
        toWeightClassId: 'mens-bantamweight',
        reason: 'UFC debut at bantamweight',
      },
    ],
  },
  {
    id: 'aljamain-sterling',
    name: 'Aljamain Sterling',
    nickname: 'Funk Master',
    imageUrl: fighterAvatar('Aljamain Sterling'),
    country: 'United States',
    record: { wins: 24, losses: 5, draws: 0 },
    weightClassIds: ['mens-featherweight', 'mens-bantamweight'],
    rankingTimeline: [
      { date: '2021-03', rank: 'C', weightClassId: 'mens-bantamweight' },
      { date: '2023-08', rank: 1, weightClassId: 'mens-bantamweight' },
    ],
    weightClassChanges: [
      {
        date: '2014-04',
        fromWeightClassId: null,
        toWeightClassId: 'mens-bantamweight',
        reason: 'UFC debut at bantamweight',
      },
      {
        date: '2024-04',
        fromWeightClassId: 'mens-bantamweight',
        toWeightClassId: 'mens-featherweight',
        reason: 'Moved up to featherweight',
      },
    ],
  },
  {
    id: 'henry-cejudo',
    name: 'Henry Cejudo',
    nickname: 'Triple C',
    imageUrl: fighterAvatar('Henry Cejudo'),
    country: 'United States',
    record: { wins: 16, losses: 3, draws: 0 },
    weightClassIds: ['mens-bantamweight', 'mens-flyweight'],
    rankingTimeline: [
      { date: '2018-08', rank: 'C', weightClassId: 'mens-flyweight' },
      { date: '2019-06', rank: 'C', weightClassId: 'mens-bantamweight' },
      { date: '2020-05', rank: 'NR', weightClassId: 'mens-bantamweight', note: 'Retired (later returned)' },
    ],
    weightClassChanges: [
      {
        date: '2014-12',
        fromWeightClassId: null,
        toWeightClassId: 'mens-flyweight',
        reason: 'UFC debut at flyweight',
      },
      {
        date: '2019-01',
        fromWeightClassId: 'mens-flyweight',
        toWeightClassId: 'mens-bantamweight',
        reason: 'Moved up; later vacated flyweight',
      },
    ],
  },
  {
    id: 'joshua-van',
    name: 'Joshua Van',
    nickname: 'The Fearless',
    imageUrl: fighterAvatar('Joshua Van'),
    country: 'Myanmar / United States',
    record: { wins: 18, losses: 2, draws: 0 },
    weightClassIds: ['mens-flyweight'],
    rankingTimeline: [
      { date: '2025-06', rank: 3, weightClassId: 'mens-flyweight' },
      { date: '2025-12', rank: 'C', weightClassId: 'mens-flyweight' },
    ],
    weightClassChanges: [
      {
        date: '2023-08',
        fromWeightClassId: null,
        toWeightClassId: 'mens-flyweight',
        reason: 'UFC debut at flyweight',
      },
    ],
  },
  {
    id: 'alexandre-pantoja',
    name: 'Alexandre Pantoja',
    nickname: 'The Cannibal',
    imageUrl: fighterAvatar('Alexandre Pantoja'),
    country: 'Brazil',
    record: { wins: 29, losses: 5, draws: 0 },
    weightClassIds: ['mens-flyweight'],
    rankingTimeline: [
      { date: '2023-07', rank: 'C', weightClassId: 'mens-flyweight' },
      { date: '2025-12', rank: 1, weightClassId: 'mens-flyweight' },
    ],
    weightClassChanges: [
      {
        date: '2017-01',
        fromWeightClassId: null,
        toWeightClassId: 'mens-flyweight',
        reason: 'UFC debut at flyweight',
      },
    ],
  },
  {
    id: 'brandon-moreno',
    name: 'Brandon Moreno',
    nickname: 'The Assassin Baby',
    imageUrl: fighterAvatar('Brandon Moreno'),
    country: 'Mexico',
    record: { wins: 23, losses: 8, draws: 2 },
    weightClassIds: ['mens-flyweight', 'mens-bantamweight'],
    rankingTimeline: [
      { date: '2021-06', rank: 'C', weightClassId: 'mens-flyweight' },
      { date: '2022-01', rank: 1, weightClassId: 'mens-flyweight' },
      { date: '2023-01', rank: 'C', weightClassId: 'mens-flyweight' },
      { date: '2023-07', rank: 2, weightClassId: 'mens-flyweight' },
    ],
    weightClassChanges: [
      {
        date: '2016-10',
        fromWeightClassId: null,
        toWeightClassId: 'mens-flyweight',
        reason: 'UFC debut at flyweight',
      },
    ],
  },
  {
    id: 'deiveson-figueiredo',
    name: 'Deiveson Figueiredo',
    nickname: 'Deus da Guerra',
    imageUrl: fighterAvatar('Deiveson Figueiredo'),
    country: 'Brazil',
    record: { wins: 24, losses: 4, draws: 1 },
    weightClassIds: ['mens-bantamweight', 'mens-flyweight'],
    rankingTimeline: [
      { date: '2020-07', rank: 'C', weightClassId: 'mens-flyweight' },
      { date: '2021-06', rank: 1, weightClassId: 'mens-flyweight' },
      { date: '2022-01', rank: 'C', weightClassId: 'mens-flyweight' },
    ],
    weightClassChanges: [
      {
        date: '2017-06',
        fromWeightClassId: null,
        toWeightClassId: 'mens-flyweight',
        reason: 'UFC debut at flyweight',
      },
      {
        date: '2023-04',
        fromWeightClassId: 'mens-flyweight',
        toWeightClassId: 'mens-bantamweight',
        reason: 'Moved up to bantamweight',
      },
    ],
  },
  {
    id: 'demetrious-johnson',
    name: 'Demetrious Johnson',
    nickname: 'Mighty Mouse',
    imageUrl: fighterAvatar('Demetrious Johnson'),
    country: 'United States',
    record: { wins: 25, losses: 3, draws: 1 },
    weightClassIds: ['mens-flyweight', 'mens-bantamweight'],
    rankingTimeline: [
      { date: '2012-09', rank: 'C', weightClassId: 'mens-flyweight' },
      { date: '2018-08', rank: 1, weightClassId: 'mens-flyweight' },
    ],
    weightClassChanges: [
      {
        date: '2011-02',
        fromWeightClassId: null,
        toWeightClassId: 'mens-bantamweight',
        reason: 'Early UFC bouts at bantamweight',
      },
      {
        date: '2012-09',
        fromWeightClassId: 'mens-bantamweight',
        toWeightClassId: 'mens-flyweight',
        reason: 'Won inaugural flyweight title',
      },
    ],
  },
  {
    id: 'mackenzie-dern',
    name: 'Mackenzie Dern',
    imageUrl: fighterAvatar('Mackenzie Dern'),
    country: 'United States / Brazil',
    record: { wins: 17, losses: 5, draws: 0 },
    weightClassIds: ['womens-strawweight'],
    rankingTimeline: [
      { date: '2024-08', rank: 3, weightClassId: 'womens-strawweight' },
      { date: '2025-10', rank: 'C', weightClassId: 'womens-strawweight' },
    ],
    weightClassChanges: [
      {
        date: '2018-10',
        fromWeightClassId: null,
        toWeightClassId: 'womens-strawweight',
        reason: 'UFC debut at strawweight',
      },
    ],
  },
  {
    id: 'zhang-weili',
    name: 'Zhang Weili',
    nickname: 'Magnum',
    imageUrl: fighterAvatar('Zhang Weili'),
    country: 'China',
    record: { wins: 25, losses: 4, draws: 0 },
    weightClassIds: ['womens-flyweight', 'womens-strawweight'],
    rankingTimeline: [
      { date: '2019-08', rank: 'C', weightClassId: 'womens-strawweight' },
      { date: '2021-04', rank: 1, weightClassId: 'womens-strawweight' },
      { date: '2022-11', rank: 'C', weightClassId: 'womens-strawweight' },
      { date: '2025-10', rank: 'NR', weightClassId: 'womens-strawweight', note: 'Vacated for WFLW' },
    ],
    weightClassChanges: [
      {
        date: '2018-08',
        fromWeightClassId: null,
        toWeightClassId: 'womens-strawweight',
        reason: 'UFC debut at strawweight',
      },
      {
        date: '2025-11',
        fromWeightClassId: 'womens-strawweight',
        toWeightClassId: 'womens-flyweight',
        reason: 'Moved up to challenge for flyweight title',
      },
    ],
  },
  {
    id: 'rose-namajunas',
    name: 'Rose Namajunas',
    nickname: 'Thug',
    imageUrl: fighterAvatar('Rose Namajunas'),
    country: 'United States',
    record: { wins: 13, losses: 7, draws: 0 },
    weightClassIds: ['womens-flyweight', 'womens-strawweight'],
    rankingTimeline: [
      { date: '2017-11', rank: 'C', weightClassId: 'womens-strawweight' },
      { date: '2019-05', rank: 1, weightClassId: 'womens-strawweight' },
      { date: '2021-04', rank: 'C', weightClassId: 'womens-strawweight' },
    ],
    weightClassChanges: [
      {
        date: '2014-12',
        fromWeightClassId: null,
        toWeightClassId: 'womens-strawweight',
        reason: 'UFC debut at strawweight',
      },
    ],
  },
  {
    id: 'carla-esparza',
    name: 'Carla Esparza',
    nickname: 'Cookie Monster',
    imageUrl: fighterAvatar('Carla Esparza'),
    country: 'United States',
    record: { wins: 19, losses: 9, draws: 0 },
    weightClassIds: ['womens-strawweight'],
    rankingTimeline: [
      { date: '2014-12', rank: 'C', weightClassId: 'womens-strawweight' },
      { date: '2022-05', rank: 'C', weightClassId: 'womens-strawweight' },
    ],
    weightClassChanges: [
      {
        date: '2014-12',
        fromWeightClassId: null,
        toWeightClassId: 'womens-strawweight',
        reason: 'Inaugural UFC strawweight champion',
      },
    ],
  },
  {
    id: 'joanna-jedrzejczyk',
    name: 'Joanna Jędrzejczyk',
    imageUrl: fighterAvatar('Joanna Jedrzejczyk'),
    country: 'Poland',
    record: { wins: 16, losses: 5, draws: 0 },
    weightClassIds: ['womens-flyweight', 'womens-strawweight'],
    rankingTimeline: [
      { date: '2015-03', rank: 'C', weightClassId: 'womens-strawweight' },
      { date: '2017-11', rank: 1, weightClassId: 'womens-strawweight' },
    ],
    weightClassChanges: [
      {
        date: '2014-07',
        fromWeightClassId: null,
        toWeightClassId: 'womens-strawweight',
        reason: 'UFC debut at strawweight',
      },
      {
        date: '2018-12',
        fromWeightClassId: 'womens-strawweight',
        toWeightClassId: 'womens-flyweight',
        reason: 'Moved up for flyweight title fight',
      },
    ],
  },
  {
    id: 'valentina-shevchenko',
    name: 'Valentina Shevchenko',
    nickname: 'Bullet',
    imageUrl: fighterAvatar('Valentina Shevchenko'),
    country: 'Kyrgyzstan',
    record: { wins: 26, losses: 4, draws: 1 },
    weightClassIds: ['womens-flyweight', 'womens-bantamweight'],
    rankingTimeline: [
      { date: '2018-12', rank: 'C', weightClassId: 'womens-flyweight' },
      { date: '2023-03', rank: 1, weightClassId: 'womens-flyweight' },
      { date: '2024-09', rank: 'C', weightClassId: 'womens-flyweight' },
    ],
    weightClassChanges: [
      {
        date: '2015-09',
        fromWeightClassId: null,
        toWeightClassId: 'womens-bantamweight',
        reason: 'UFC debut at bantamweight',
      },
      {
        date: '2018-12',
        fromWeightClassId: 'womens-bantamweight',
        toWeightClassId: 'womens-flyweight',
        reason: 'Moved down and won flyweight title',
      },
    ],
  },
  {
    id: 'alexa-grasso',
    name: 'Alexa Grasso',
    imageUrl: fighterAvatar('Alexa Grasso'),
    country: 'Mexico',
    record: { wins: 16, losses: 4, draws: 1 },
    weightClassIds: ['womens-flyweight', 'womens-strawweight'],
    rankingTimeline: [
      { date: '2023-03', rank: 'C', weightClassId: 'womens-flyweight' },
      { date: '2024-09', rank: 1, weightClassId: 'womens-flyweight' },
    ],
    weightClassChanges: [
      {
        date: '2016-11',
        fromWeightClassId: null,
        toWeightClassId: 'womens-strawweight',
        reason: 'UFC debut at strawweight',
      },
      {
        date: '2020-08',
        fromWeightClassId: 'womens-strawweight',
        toWeightClassId: 'womens-flyweight',
        reason: 'Moved up to flyweight',
      },
    ],
  },
  {
    id: 'nicco-montano',
    name: 'Nicco Montaño',
    imageUrl: fighterAvatar('Nicco Montano'),
    country: 'United States',
    record: { wins: 9, losses: 3, draws: 0 },
    weightClassIds: ['womens-flyweight'],
    rankingTimeline: [
      { date: '2017-12', rank: 'C', weightClassId: 'womens-flyweight' },
      { date: '2018-09', rank: 'NR', weightClassId: 'womens-flyweight', note: 'Stripped' },
    ],
    weightClassChanges: [
      {
        date: '2017-12',
        fromWeightClassId: null,
        toWeightClassId: 'womens-flyweight',
        reason: 'Inaugural women\'s flyweight champion (TUF 26)',
      },
    ],
  },
  {
    id: 'kayla-harrison',
    name: 'Kayla Harrison',
    imageUrl: fighterAvatar('Kayla Harrison'),
    country: 'United States',
    record: { wins: 19, losses: 1, draws: 0 },
    weightClassIds: ['womens-bantamweight'],
    rankingTimeline: [
      { date: '2024-04', rank: 3, weightClassId: 'womens-bantamweight' },
      { date: '2025-06', rank: 'C', weightClassId: 'womens-bantamweight' },
    ],
    weightClassChanges: [
      {
        date: '2024-04',
        fromWeightClassId: null,
        toWeightClassId: 'womens-bantamweight',
        reason: 'UFC debut at bantamweight',
      },
    ],
  },
  {
    id: 'julianna-pena',
    name: 'Julianna Peña',
    nickname: 'The Venezuelan Vixen',
    imageUrl: fighterAvatar('Julianna Pena'),
    country: 'United States',
    record: { wins: 12, losses: 6, draws: 0 },
    weightClassIds: ['womens-bantamweight'],
    rankingTimeline: [
      { date: '2021-12', rank: 'C', weightClassId: 'womens-bantamweight' },
      { date: '2022-07', rank: 1, weightClassId: 'womens-bantamweight' },
      { date: '2024-10', rank: 'C', weightClassId: 'womens-bantamweight' },
      { date: '2025-06', rank: 1, weightClassId: 'womens-bantamweight' },
    ],
    weightClassChanges: [
      {
        date: '2013-11',
        fromWeightClassId: null,
        toWeightClassId: 'womens-bantamweight',
        reason: 'UFC debut at bantamweight',
      },
    ],
  },
  {
    id: 'raquel-pennington',
    name: 'Raquel Pennington',
    nickname: 'Rocky',
    imageUrl: fighterAvatar('Raquel Pennington'),
    country: 'United States',
    record: { wins: 16, losses: 9, draws: 0 },
    weightClassIds: ['womens-bantamweight'],
    rankingTimeline: [
      { date: '2024-01', rank: 'C', weightClassId: 'womens-bantamweight' },
      { date: '2024-10', rank: 2, weightClassId: 'womens-bantamweight' },
    ],
    weightClassChanges: [
      {
        date: '2013-11',
        fromWeightClassId: null,
        toWeightClassId: 'womens-bantamweight',
        reason: 'UFC debut at bantamweight',
      },
    ],
  },
  {
    id: 'amanda-nunes',
    name: 'Amanda Nunes',
    nickname: 'The Lioness',
    imageUrl: fighterAvatar('Amanda Nunes'),
    country: 'Brazil',
    record: { wins: 23, losses: 5, draws: 0 },
    weightClassIds: ['womens-featherweight', 'womens-bantamweight'],
    rankingTimeline: [
      { date: '2016-07', rank: 'C', weightClassId: 'womens-bantamweight' },
      { date: '2018-12', rank: 'C', weightClassId: 'womens-featherweight' },
      { date: '2021-12', rank: 1, weightClassId: 'womens-bantamweight' },
      { date: '2022-07', rank: 'C', weightClassId: 'womens-bantamweight' },
      { date: '2023-06', rank: 'NR', weightClassId: 'womens-bantamweight', note: 'Retired' },
    ],
    weightClassChanges: [
      {
        date: '2013-08',
        fromWeightClassId: null,
        toWeightClassId: 'womens-bantamweight',
        reason: 'UFC debut at bantamweight',
      },
      {
        date: '2018-12',
        fromWeightClassId: 'womens-bantamweight',
        toWeightClassId: 'womens-featherweight',
        reason: 'Won featherweight title (two-division champ)',
      },
    ],
  },
  {
    id: 'holly-holm',
    name: 'Holly Holm',
    nickname: "The Preacher's Daughter",
    imageUrl: fighterAvatar('Holly Holm'),
    country: 'United States',
    record: { wins: 15, losses: 7, draws: 0 },
    weightClassIds: ['womens-featherweight', 'womens-bantamweight'],
    rankingTimeline: [
      { date: '2015-11', rank: 'C', weightClassId: 'womens-bantamweight' },
      { date: '2016-03', rank: 1, weightClassId: 'womens-bantamweight' },
    ],
    weightClassChanges: [
      {
        date: '2015-02',
        fromWeightClassId: null,
        toWeightClassId: 'womens-bantamweight',
        reason: 'UFC debut at bantamweight',
      },
    ],
  },
  {
    id: 'cris-cyborg',
    name: 'Cris Cyborg',
    imageUrl: fighterAvatar('Cris Cyborg'),
    country: 'Brazil',
    record: { wins: 28, losses: 2, draws: 0, noContests: 1 },
    weightClassIds: ['womens-featherweight'],
    rankingTimeline: [
      { date: '2017-07', rank: 'C', weightClassId: 'womens-featherweight' },
      { date: '2018-12', rank: 1, weightClassId: 'womens-featherweight' },
    ],
    weightClassChanges: [
      {
        date: '2016-01',
        fromWeightClassId: null,
        toWeightClassId: 'womens-featherweight',
        reason: 'UFC debut path into featherweight',
      },
    ],
  },
  {
    id: 'germaine-de-randamie',
    name: 'Germaine de Randamie',
    nickname: 'The Iron Lady',
    imageUrl: fighterAvatar('Germaine de Randamie'),
    country: 'Netherlands',
    record: { wins: 10, losses: 5, draws: 0 },
    weightClassIds: ['womens-featherweight', 'womens-bantamweight'],
    rankingTimeline: [
      { date: '2017-02', rank: 'C', weightClassId: 'womens-featherweight' },
      { date: '2017-06', rank: 'NR', weightClassId: 'womens-featherweight', note: 'Vacated' },
    ],
    weightClassChanges: [
      {
        date: '2013-02',
        fromWeightClassId: null,
        toWeightClassId: 'womens-bantamweight',
        reason: 'UFC debut at bantamweight',
      },
      {
        date: '2017-02',
        fromWeightClassId: 'womens-bantamweight',
        toWeightClassId: 'womens-featherweight',
        reason: 'Won inaugural women\'s featherweight title',
      },
    ],
  },
]

export const FIGHTERS: Fighter[] = FIGHTERS_RAW.map((fighter) => ({
  ...fighter,
  heightCm: fighterHeightCm(fighter.id),
}))

export const fightersById = Object.fromEntries(
  FIGHTERS.map((fighter) => [fighter.id, fighter]),
) as Record<string, Fighter>
