import type { WeightClass } from './types'

/**
 * Official UFC division limits.
 * Sources: UFC.com weight-class explainer; conventional kg rounding used by UFC media.
 */
export const WEIGHT_CLASSES: WeightClass[] = [
  {
    id: 'mens-flyweight',
    name: 'Flyweight',
    shortName: 'Flyweight',
    gender: 'men',
    limitLb: 125,
    limitKg: 56.7,
    minLb: 116,
    order: 1,
  },
  {
    id: 'mens-bantamweight',
    name: 'Bantamweight',
    shortName: 'Bantamweight',
    gender: 'men',
    limitLb: 135,
    limitKg: 61.2,
    minLb: 126,
    order: 2,
  },
  {
    id: 'mens-featherweight',
    name: 'Featherweight',
    shortName: 'Featherweight',
    gender: 'men',
    limitLb: 145,
    limitKg: 65.8,
    minLb: 136,
    order: 3,
  },
  {
    id: 'mens-lightweight',
    name: 'Lightweight',
    shortName: 'Lightweight',
    gender: 'men',
    limitLb: 155,
    limitKg: 70.3,
    minLb: 146,
    order: 4,
  },
  {
    id: 'mens-welterweight',
    name: 'Welterweight',
    shortName: 'Welterweight',
    gender: 'men',
    limitLb: 170,
    limitKg: 77.1,
    minLb: 156,
    order: 5,
  },
  {
    id: 'mens-middleweight',
    name: 'Middleweight',
    shortName: 'Middleweight',
    gender: 'men',
    limitLb: 185,
    limitKg: 83.9,
    minLb: 171,
    order: 6,
  },
  {
    id: 'mens-light-heavyweight',
    name: 'Light Heavyweight',
    shortName: 'Light Heavyweight',
    gender: 'men',
    limitLb: 205,
    limitKg: 93.0,
    minLb: 186,
    order: 7,
  },
  {
    id: 'mens-heavyweight',
    name: 'Heavyweight',
    shortName: 'Heavyweight',
    gender: 'men',
    limitLb: 265,
    limitKg: 120.2,
    minLb: 206,
    order: 8,
  },
  {
    id: 'womens-strawweight',
    name: "Women's Strawweight",
    shortName: 'Strawweight',
    gender: 'women',
    limitLb: 115,
    limitKg: 52.2,
    minLb: null,
    order: 9,
  },
  {
    id: 'womens-flyweight',
    name: "Women's Flyweight",
    shortName: 'Flyweight',
    gender: 'women',
    limitLb: 125,
    limitKg: 56.7,
    minLb: 116,
    order: 10,
  },
  {
    id: 'womens-bantamweight',
    name: "Women's Bantamweight",
    shortName: 'Bantamweight',
    gender: 'women',
    limitLb: 135,
    limitKg: 61.2,
    minLb: 126,
    order: 11,
  },
  {
    id: 'womens-featherweight',
    name: "Women's Featherweight",
    shortName: 'Featherweight',
    gender: 'women',
    limitLb: 145,
    limitKg: 65.8,
    minLb: 136,
    order: 12,
  },
]
