/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../pages/__root'
import { Route as IndexRouteImport } from './../pages/index'
import { Route as WeightFinderRouteImport } from './../pages/weight-finder'
import { Route as FightersFighterIdRouteImport } from './../pages/fighters.$fighterId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeightFinderRoute = WeightFinderRouteImport.update({
  id: '/weight-finder',
  path: '/weight-finder',
  getParentRoute: () => rootRouteImport,
} as any)
const FightersFighterIdRoute = FightersFighterIdRouteImport.update({
  id: '/fighters/$fighterId',
  path: '/fighters/$fighterId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/weight-finder': typeof WeightFinderRoute
  '/fighters/$fighterId': typeof FightersFighterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/weight-finder': typeof WeightFinderRoute
  '/fighters/$fighterId': typeof FightersFighterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/weight-finder': typeof WeightFinderRoute
  '/fighters/$fighterId': typeof FightersFighterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/weight-finder' | '/fighters/$fighterId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/weight-finder' | '/fighters/$fighterId'
  id: '__root__' | '/' | '/weight-finder' | '/fighters/$fighterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WeightFinderRoute: typeof WeightFinderRoute
  FightersFighterIdRoute: typeof FightersFighterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weight-finder': {
      id: '/weight-finder'
      path: '/weight-finder'
      fullPath: '/weight-finder'
      preLoaderRoute: typeof WeightFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fighters/$fighterId': {
      id: '/fighters/$fighterId'
      path: '/fighters/$fighterId'
      fullPath: '/fighters/$fighterId'
      preLoaderRoute: typeof FightersFighterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WeightFinderRoute: WeightFinderRoute,
  FightersFighterIdRoute: FightersFighterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
